// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5uZwJitiAWwRVRJoLyo8zXZTvJZnFzrU',
    appId: '1:330443921218:web:51c25d8dae47945ad3dadb',
    messagingSenderId: '330443921218',
    projectId: 'tech-mobile-store',
    authDomain: 'tech-mobile-store.firebaseapp.com',
    storageBucket: 'tech-mobile-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn-UU8cu9ifedtnIMKTC0qhwA6sAbAiiI',
    appId: '1:330443921218:android:efc1093d0847ee53d3dadb',
    messagingSenderId: '330443921218',
    projectId: 'tech-mobile-store',
    storageBucket: 'tech-mobile-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-RQgkQtt-ZG-zDu3dwRwCaTxBYEOEiQ',
    appId: '1:330443921218:ios:58ee58f2c09400fad3dadb',
    messagingSenderId: '330443921218',
    projectId: 'tech-mobile-store',
    storageBucket: 'tech-mobile-store.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi-RQgkQtt-ZG-zDu3dwRwCaTxBYEOEiQ',
    appId: '1:330443921218:ios:58ee58f2c09400fad3dadb',
    messagingSenderId: '330443921218',
    projectId: 'tech-mobile-store',
    storageBucket: 'tech-mobile-store.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5uZwJitiAWwRVRJoLyo8zXZTvJZnFzrU',
    appId: '1:330443921218:web:ce489581976ebf5ad3dadb',
    messagingSenderId: '330443921218',
    projectId: 'tech-mobile-store',
    authDomain: 'tech-mobile-store.firebaseapp.com',
    storageBucket: 'tech-mobile-store.firebasestorage.app',
  );
}
